name: kubrick
description: "Speech to Text AI Transcription App"
publish_to: 'none'
version: 0.1.4

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  uuid: ^4.4.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  http: ^1.2.1
  rxdart: ^0.27.7
  tuple: ^2.0.2
  loading_indicator: ^3.1.1
  get: ^4.6.6
  file_picker: ^8.0.5
  http_parser: ^4.0.0
  connectivity_plus: ^6.0.3
  flutter_launcher_icons: ^0.13.1
  open_file: ^3.5.0+1
  awesome_snackbar_content: ^0.1.3
  shared_preferences: ^2.3.1
  audio_waveforms: ^1.0.5
  flutter_secure_storage: ^9.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  image_path_ios: "assets/icons/kubrick_logo.png"
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#333333"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/