name: kubrick
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  record: ^5.0.5
  uuid: ^4.4.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  just_audio: ^0.9.38
  intl: ^0.19.0
  audio_video_progress_bar: ^2.0.2
  http: ^1.2.1
  rxdart: ^0.27.7
  tuple: ^2.0.2
  google_fonts: ^6.2.1
  loading_indicator: ^3.1.1
  get: ^4.6.6
  file_picker: ^8.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
